version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - DATABASE_URL=mysql://root:secret@db:3306/app_dtb
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app_dtb
    ports:
      - 33061:3306 #host:container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: